<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_09_Artikel 1</name>
   <tag></tag>
   <elementGuidId>7468f92e-0bc9-4350-87ca-58837c36a3fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab1']/div/div/div/div/p[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05e166a3-2a58-49ee-96b2-153dc82c23fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>0b0c139a-dd23-445a-97a1-d36224b62916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mitsuilease.co.id/companys-activity-corporate-social-responsibility/6</value>
      <webElementGuid>3579738c-5bc5-44ee-9456-3fe4b6b24e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f35de9c3-a31c-4a36-b991-2140835b0b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                                                            Selengkapnya
                                                                                                                    </value>
      <webElementGuid>c9aeeffa-da22-475a-a757-e42690ca5216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;thumbnail&quot;]/div[@class=&quot;caption&quot;]/p[2]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>44e87244-4ad0-486b-82f5-03223971f5ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div/div/div/p[2]/a</value>
      <webElementGuid>9ef069dc-59dd-45ff-8c97-171a10140d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Selengkapnya')]</value>
      <webElementGuid>db43b680-2df7-46fe-ab32-1c1bf74840a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donor Darah MLCI 2023: Darah yang Berharga, Darah yang Bantu Sesama'])[1]/following::a[1]</value>
      <webElementGuid>4821e071-de32-4eaa-ac7d-ebeb3fd6e416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senin, 9 Oktober 2023'])[1]/following::a[1]</value>
      <webElementGuid>a330b23d-3692-451d-b4e3-7f3d8de20140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sabtu, 17 Juni 2023'])[1]/preceding::a[1]</value>
      <webElementGuid>fd6be355-610e-4200-9b13-dc7e177aac65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Webinar Literasi Keuangan 2023 Semester I: Mengenal Perusahaan Pembiayaan Lebih Dekat'])[1]/preceding::a[1]</value>
      <webElementGuid>76b063a6-aad7-49d2-91a2-db7fa2b6d1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selengkapnya']/parent::*</value>
      <webElementGuid>fe1b2d3e-1bc0-4a2a-b07e-ffa36e336eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mitsuilease.co.id/companys-activity-corporate-social-responsibility/6')]</value>
      <webElementGuid>f9661bce-7c48-4d9f-a497-12ccba55a1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>70197b37-d3e0-45bf-af98-fb9297773f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mitsuilease.co.id/companys-activity-corporate-social-responsibility/6' and (text() = '
                                                                                                                            Selengkapnya
                                                                                                                    ' or . = '
                                                                                                                            Selengkapnya
                                                                                                                    ')]</value>
      <webElementGuid>24bc8d2b-77b4-4976-963e-2a6bc9e12396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
