<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_25_Kantor Selain Kantor Cabang (KSKC)</name>
   <tag></tag>
   <elementGuidId>965e3163-99db-4b63-bd00-63c877476921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/section/div/div/div/div/div/ul/li[8]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5e236bd2-6efb-4149-8812-606ad90ad2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mitsuilease.co.id/non-cabang</value>
      <webElementGuid>ae59fe4a-87fc-4752-b786-e55013f33f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kantor Selain Kantor Cabang (KSKC)</value>
      <webElementGuid>0ba981f6-97d5-41a4-80fc-9ec60c8c843e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/section[@class=&quot;kopa-area kopa-area-31&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-2 col-xs-12&quot;]/div[@class=&quot;widget clearfix widget_nav_menu&quot;]/div[@class=&quot;menu-menu-container&quot;]/ul[@class=&quot;menu&quot;]/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page&quot;]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>21161f8e-65e3-472c-bd44-5dfe9d5ed874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/section/div/div/div/div/div/ul/li[8]/ul/li[3]/a</value>
      <webElementGuid>ad2c8c7c-3f75-446f-8a91-d0162cd3d30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Kantor Selain Kantor Cabang (KSKC)')])[3]</value>
      <webElementGuid>c8038859-0693-40ef-be46-2e793b0e8a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantor Cabang'])[4]/following::a[1]</value>
      <webElementGuid>ce986df4-cb6c-4a34-a2c2-f490b488e195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantor Pusat'])[3]/following::a[2]</value>
      <webElementGuid>5d80181a-7062-4347-a3f6-1edaf078d25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Keberlanjutan'])[3]/preceding::a[1]</value>
      <webElementGuid>64530eb4-243f-41e6-9efa-92d534b6d37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantor Cabang'])[5]/preceding::a[2]</value>
      <webElementGuid>80a442bd-5ab7-4ce1-b49d-cd84b658236c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.mitsuilease.co.id/non-cabang')])[3]</value>
      <webElementGuid>11aaa182-2565-4513-809e-ddca6e91d557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[8]/ul/li[3]/a</value>
      <webElementGuid>23558485-26db-446d-b9f7-61f3e66bf9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mitsuilease.co.id/non-cabang' and (text() = 'Kantor Selain Kantor Cabang (KSKC)' or . = 'Kantor Selain Kantor Cabang (KSKC)')]</value>
      <webElementGuid>7013fcf2-d4a8-4bf7-9e8b-500ceb65d9c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
