<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_14_Artikel 6</name>
   <tag></tag>
   <elementGuidId>9e8b00a9-1935-437a-9712-8310c0e1a143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab1']/div[2]/div[3]/div/div/p[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de307a79-3e4f-429f-b078-430d60ade3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>1e9c86db-ded5-4996-b72c-e1b5ddbafde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mitsuilease.co.id/companys-activity-corporate-social-responsibility/3</value>
      <webElementGuid>2d3579f3-274c-49df-8bf2-c1a35650eb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4e84769-bc54-4472-be7b-ae11c45b5264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                                                            Selengkapnya
                                                                                                                    </value>
      <webElementGuid>3976fc17-1509-4fa6-b08d-344218493335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;thumbnail&quot;]/div[@class=&quot;caption&quot;]/p[2]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>1af6da18-069d-452a-8dca-dbdf6db08ff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div[2]/div[3]/div/div/p[2]/a</value>
      <webElementGuid>539a7edf-b32e-48d8-b986-e89d1610950b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Selengkapnya')])[6]</value>
      <webElementGuid>a5a47dca-e591-4a5a-a70c-7aa8fe164ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MLCI Berbagi 2021: Demi Kesehatan, Pendidikan, dan Hidup yang Lebih Sejahtera'])[1]/following::a[1]</value>
      <webElementGuid>71a431bb-386b-49a1-ba92-3619373d3276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rabu, 8 Desember 2021'])[1]/following::a[1]</value>
      <webElementGuid>bb60f7bc-d2fc-4caf-9ad8-7375be5212cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[2]/preceding::a[1]</value>
      <webElementGuid>6b22d501-1cad-4b28-8c4a-6f008c37be78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROFIL'])[3]/preceding::a[2]</value>
      <webElementGuid>326a1f4d-55b0-41e7-a877-5420b070a955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mitsuilease.co.id/companys-activity-corporate-social-responsibility/3')]</value>
      <webElementGuid>a2f3a44a-32a8-4188-bb72-9c591702ee79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/p[2]/a</value>
      <webElementGuid>94cbeaec-ab40-4d82-a282-a5b36fae512d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mitsuilease.co.id/companys-activity-corporate-social-responsibility/3' and (text() = '
                                                                                                                            Selengkapnya
                                                                                                                    ' or . = '
                                                                                                                            Selengkapnya
                                                                                                                    ')]</value>
      <webElementGuid>8ad575fa-a6cf-4984-9b3a-ab0f7caa43d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
