<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_12_Artikel 4</name>
   <tag></tag>
   <elementGuidId>eb1070d4-5bcf-46d9-9668-dc44e8190af3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab1']/div[2]/div/div/div/p[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f73823d2-25f1-45b0-871e-c107eb18d4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>4ef15ae5-377a-4243-9b01-07794713e3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mitsuilease.co.id/companys-activity-corporate-social-responsibility/1</value>
      <webElementGuid>ed55b527-0211-4555-9e74-3cccadcc3565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35864d17-7464-42d8-96b2-59e035810528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                                                            Selengkapnya
                                                                                                                    </value>
      <webElementGuid>5a796603-4d34-4ae5-8d53-1465849a3437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;thumbnail&quot;]/div[@class=&quot;caption&quot;]/p[2]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>cf1a2211-32d8-495c-97c4-b930035eaff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div[2]/div/div/div/p[2]/a</value>
      <webElementGuid>1733b75a-21cd-4888-9178-db68430355f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Selengkapnya')])[4]</value>
      <webElementGuid>792b47df-0c6f-4825-82e2-785cd59bd209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menyambut 30 Tahun, Mitsui Leasing Capital Indonesia Berbagi Kebahagiaan dengan 300 Pekerja Rentan'])[1]/following::a[1]</value>
      <webElementGuid>e0bb0a80-477b-4754-a484-10fd46b46113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rabu, 24 Agustus 2022'])[1]/following::a[1]</value>
      <webElementGuid>4c0c24dc-09af-4269-8b8d-17599f2ab674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sabtu, 25 Juni 2022'])[1]/preceding::a[1]</value>
      <webElementGuid>b89162e7-e273-4975-b638-0fd041ad5232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selengkapnya'])[5]/preceding::a[1]</value>
      <webElementGuid>14f99e93-70a1-418b-92c0-f7e7c46bf2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mitsuilease.co.id/companys-activity-corporate-social-responsibility/1')]</value>
      <webElementGuid>69cc4089-ddb6-4d48-a4cf-b00d2c86717d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p[2]/a</value>
      <webElementGuid>ef274faa-9ec7-400d-9929-7a1ed3259178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mitsuilease.co.id/companys-activity-corporate-social-responsibility/1' and (text() = '
                                                                                                                            Selengkapnya
                                                                                                                    ' or . = '
                                                                                                                            Selengkapnya
                                                                                                                    ')]</value>
      <webElementGuid>9f9882f5-f4ce-426f-b511-c0ab8201f32b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
