<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FAQ_btn-title</name>
   <tag></tag>
   <elementGuidId>82a34dda-1c5a-431c-b8d2-94d3478df75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordion']/div/div/h4/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.btn-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>09289667-c6a8-4d41-9134-8fc3904637b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-title</value>
      <webElementGuid>80c4afad-fc24-42ee-8fa1-f4ac581c2525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-heading&quot;]/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]/span[@class=&quot;btn-title&quot;]</value>
      <webElementGuid>79386213-fb3f-476c-919a-63c5ac65e499</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div/h4/a/span</value>
      <webElementGuid>c2dc105f-dee7-4139-8a85-78d80bad3c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a/span</value>
      <webElementGuid>e8e2f2eb-4d70-4cd6-aea1-01a0cd0ed8ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
