<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KomentarSaran_submit-comment</name>
   <tag></tag>
   <elementGuidId>e6fc6c4f-d236-4f0c-86cd-3287607b13d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submit-comment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit-comment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adc7f085-b2a6-46d5-8c1c-4b705fbfc819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>115e04ae-bf43-44ac-ad51-99f5898cca20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-submit</value>
      <webElementGuid>0316e8ed-5535-4013-8e62-919f365b018f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-comment</value>
      <webElementGuid>2543a19a-e846-4f0e-a41d-eb88e0ecf4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Kirim Komentar/Saran</value>
      <webElementGuid>b9935d99-d544-4729-99cd-5dec8067b4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-comment&quot;)</value>
      <webElementGuid>0d89db2b-1071-4d1a-a549-0c3ecaaeee23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submit-comment']</value>
      <webElementGuid>7094dea5-5961-4f81-8949-1b944111ee8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='bootstrapSelectForm']/div[3]/div/p/input</value>
      <webElementGuid>6b776cc9-5a8c-4957-aa26-79b86d174008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p/input</value>
      <webElementGuid>65035e3a-a08a-4619-959c-04a2f317715f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'submit-comment']</value>
      <webElementGuid>15e5d98d-447d-44ed-b8e8-6cd71800be52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
