<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp.4.893.900.000,00_btn input-submit</name>
   <tag></tag>
   <elementGuidId>979044e7-9f0c-46ab-9eab-231870287527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Permohonan Kredit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.input-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d9d61f0-c973-4c5e-8e7a-8adc323c25b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>23751227-130c-4d9c-8a43-855f0f338d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn input-submit</value>
      <webElementGuid>c5b76b31-58d3-4376-acbb-102e27085db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Permohonan Kredit</value>
      <webElementGuid>4c1a8de0-7d46-4283-95ac-51f46be09e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form2a&quot;)/table[1]/tbody[1]/tr[12]/td[1]/input[@class=&quot;btn input-submit&quot;]</value>
      <webElementGuid>3e37dc15-79ba-4724-b85e-a5d7ede5af9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Permohonan Kredit']</value>
      <webElementGuid>7287bf79-2d93-495c-866b-62de689f9dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2a']/table/tbody/tr[12]/td/input</value>
      <webElementGuid>a8090817-37db-4b99-ae2d-ad519d64ed1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td/input</value>
      <webElementGuid>c57f0a35-0d5c-41de-8aec-48d664a3a587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>33e75d0b-004f-41c1-9f79-70413e77f419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
