<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_14_Kantor Selain Kantor Cabang (KSKC)</name>
   <tag></tag>
   <elementGuidId>8e13afb5-bbcd-44ca-9e32-123966907e48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.sfHover > #main-menu > li.sfHover > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>994b9356-43e8-45b6-ade7-3734b62dedfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mitsuilease.co.id/non-cabang</value>
      <webElementGuid>a9356ab3-e52b-4c2d-9547-0e5b45b79731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kantor Selain Kantor Cabang (KSKC)</value>
      <webElementGuid>8196a48f-d969-4b8c-9df7-b7d1608cf9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/ul[@id=&quot;main-menu&quot;]/li[@class=&quot;sfHover&quot;]/ul[1]/li[@class=&quot;sfHover&quot;]/ul[@id=&quot;main-menu&quot;]/li[@class=&quot;sfHover&quot;]/a[1]</value>
      <webElementGuid>4bb09486-f23f-45da-8f12-29bf473449a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li[3]/a</value>
      <webElementGuid>edad4263-88e8-4dc0-8699-3d54681843ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kantor Selain Kantor Cabang (KSKC)')]</value>
      <webElementGuid>e8030084-4fee-4b83-a086-0464de2a629a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantor Cabang'])[1]/following::a[1]</value>
      <webElementGuid>c2c2be0a-7424-481f-922d-b4fe7f1b1241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantor Pusat'])[1]/following::a[2]</value>
      <webElementGuid>993e99b4-be4c-4a27-9f03-d417661747a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Keberlanjutan'])[1]/preceding::a[1]</value>
      <webElementGuid>31757845-bf99-4ecb-bd60-12ddb419894b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUK'])[1]/preceding::a[2]</value>
      <webElementGuid>e05572bd-3826-46fe-b9a2-7289d54de961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kantor Selain Kantor Cabang (KSKC)']/parent::*</value>
      <webElementGuid>9e82e643-aa36-4317-8d6a-1149a3020b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mitsuilease.co.id/non-cabang')]</value>
      <webElementGuid>e62e9ec3-74ca-4db0-bbed-c64451bcd491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[3]/a</value>
      <webElementGuid>75ed32b2-6679-4925-bce9-ee51a861a5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mitsuilease.co.id/non-cabang' and (text() = 'Kantor Selain Kantor Cabang (KSKC)' or . = 'Kantor Selain Kantor Cabang (KSKC)')]</value>
      <webElementGuid>57250bc7-b873-4d43-a5d7-b71eba805bf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
