<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_02_span FAQ</name>
   <tag></tag>
   <elementGuidId>7b88845b-3105-49b5-8013-38fa4770569f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.btn-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordion']/div/div/h4/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f878974a-228a-44c5-a016-eab466a258e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-title</value>
      <webElementGuid>aee07704-ff2a-47a8-944c-0345f002d492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-heading&quot;]/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]/span[@class=&quot;btn-title&quot;]</value>
      <webElementGuid>1c47890a-b30c-4144-8b99-8d5fc2f8fa60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div/h4/a/span</value>
      <webElementGuid>faf8e4aa-8af6-4098-a5d8-8ff0381a4e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a/span</value>
      <webElementGuid>f0f4bfac-1a6b-4272-8bef-e43a4ddee884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
