<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PR List</name>
   <tag></tag>
   <elementGuidId>c13796c5-dfda-4560-aef9-b234f44b7727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/table/thead/tr/td/div/h1/div/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aa5f9c32-5bb4-462f-8124-ac11ffdd82bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../module_pr/home.php</value>
      <webElementGuid>9c292294-579e-4f74-9b28-2c28b8bb723a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>7045cd1c-ad7d-43c1-905f-cedc5a0c7ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PR List</value>
      <webElementGuid>34de1196-39f2-47f2-854f-410197701531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/table[@class=&quot;page&quot;]/thead[@class=&quot;header&quot;]/tr[1]/td[1]/div[@class=&quot;title&quot;]/h1[1]/div[1]/p[1]/a[1]</value>
      <webElementGuid>45365e9e-6b44-464a-9520-9ee528cbe95a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/table/thead/tr/td/div/h1/div/p/a</value>
      <webElementGuid>20b75b32-5318-484c-9d80-c31ccae6e4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PR List')]</value>
      <webElementGuid>7b9dc902-7ead-4d15-b6ea-0ca8ef82ead7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME'])[1]/preceding::a[1]</value>
      <webElementGuid>811a9cb2-b6cb-4203-a3f5-6f4edc20b025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket Onhand'])[1]/preceding::a[2]</value>
      <webElementGuid>207fb1f4-7488-4ff3-b290-e7273b2b13e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PR List']/parent::*</value>
      <webElementGuid>29a093cc-1bd1-4196-b724-27b7bbc5bebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../module_pr/home.php')]</value>
      <webElementGuid>0caf8bfe-5f02-44d9-baf6-82dfd1e891f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>d900417f-272e-44fc-bab6-cc5488f666c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../module_pr/home.php' and (text() = 'PR List' or . = 'PR List')]</value>
      <webElementGuid>66543808-0c32-4d82-b401-36eeb4b74ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
