<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_E-Ticketing_icon-arrow-right icon-large</name>
   <tag></tag>
   <elementGuidId>57a91f0b-e51b-4af9-a81a-ac38c2c95564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-arrow-right.icon-large</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b7639eaf-4918-4ec8-a798-b8033e2f16b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-arrow-right icon-large</value>
      <webElementGuid>3e008008-619c-4fe4-8677-67d791555b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js boxshadow pointerevents placeholder&quot;]/body[1]/div[@class=&quot;container&quot;]/section[@class=&quot;main&quot;]/form[@class=&quot;form-1&quot;]/p[@class=&quot;submit&quot;]/button[1]/i[@class=&quot;icon-arrow-right icon-large&quot;]</value>
      <webElementGuid>3a108ee6-e68f-4c15-8f0f-941a08eb6283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>7c17fe70-1625-4286-9e7c-0cab2e356987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
