<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-Ticketing_username</name>
   <tag></tag>
   <elementGuidId>72d8c440-50eb-4e26-a9af-b4f83e7e0450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='username'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.field > input[name=&quot;username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>380f9be0-54a5-485a-93ff-932652853053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c41a334b-63a0-4b3e-a750-d605d95e7d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>8c2148fc-c86b-423f-aa77-b3aa1e6e1bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>ba43d5b3-61a0-414c-8c18-404284b8fd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js boxshadow pointerevents placeholder&quot;]/body[1]/div[@class=&quot;container&quot;]/section[@class=&quot;main&quot;]/form[@class=&quot;form-1&quot;]/p[@class=&quot;field&quot;]/input[1]</value>
      <webElementGuid>5b7c7bc2-e0cd-4e50-9e8f-6e23277346f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='username'])[2]</value>
      <webElementGuid>eeeba795-80a8-49d0-9988-e4f2e503cae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/form/p/input</value>
      <webElementGuid>f62b77c2-2a5c-4fd7-9614-7b57c157df4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'username' and @placeholder = 'Username']</value>
      <webElementGuid>f2d6de1d-d59d-47a1-8289-c04dcc680c41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
