<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Allahmad_sultoniAndreas MichaelARDIA_d2b35b</name>
   <tag></tag>
   <elementGuidId>64835a72-cb22-429e-97d8-8150e7c079c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pic</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>48037a79-5f7b-4aeb-a653-f50ff255b88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pic</value>
      <webElementGuid>0edd706a-f6ef-487f-b0ee-0697d506fc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pic</value>
      <webElementGuid>106afd49-28c6-46ab-beda-39d852ade766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>getdata()</value>
      <webElementGuid>57651eff-3b46-42e1-ad15-0944ae818ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputan</value>
      <webElementGuid>e3cbd985-3e05-4aa4-b3f1-9c2352ed42f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		  Allahmad_sultoniAndreas MichaelARDIAN WIBOWODEDE KURNIAWANEni SusilowatiJESSEN YAPUTRA SETIAWANSEPTI MAULITAYogi Firmansyah    </value>
      <webElementGuid>88df155b-3c86-48d4-bcbe-be85142f8dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pic&quot;)</value>
      <webElementGuid>06764986-e420-4697-8646-67652b4a0634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Test PR List/Page_MLCI - PR LIST/iframe_LOGOUT_main1</value>
      <webElementGuid>1bcd1608-e6af-45e6-a8cf-1719825614b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pic']</value>
      <webElementGuid>33689da7-add5-46d2-8ddb-50956843df8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/table/tbody/tr/td[2]/select</value>
      <webElementGuid>99e3fe29-4777-48ca-af02-e5254b97fefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIC'])[1]/following::select[1]</value>
      <webElementGuid>7cd8af9b-d3b0-473b-b1cf-70aefd7f1b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[1]/preceding::select[1]</value>
      <webElementGuid>da47b168-f3e5-4b16-94a9-9022c2794bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item'])[1]/preceding::select[1]</value>
      <webElementGuid>691fbf66-0f7a-42a3-a909-a152df5be385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>eba5f62e-8ea8-42de-a03e-38d21e1ccc3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pic' and @name = 'pic' and (text() = '
		  Allahmad_sultoniAndreas MichaelARDIAN WIBOWODEDE KURNIAWANEni SusilowatiJESSEN YAPUTRA SETIAWANSEPTI MAULITAYogi Firmansyah    ' or . = '
		  Allahmad_sultoniAndreas MichaelARDIAN WIBOWODEDE KURNIAWANEni SusilowatiJESSEN YAPUTRA SETIAWANSEPTI MAULITAYogi Firmansyah    ')]</value>
      <webElementGuid>f4af9c6f-f45a-406d-a016-ccbcc32d27e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
