<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_09_Pilih Tipe Mobil</name>
   <tag></tag>
   <elementGuidId>334346ee-721e-4a08-bab6-fb084a198374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tipe_mobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipe_mobil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e33d4378-b0ea-4da7-a17d-46cf835ca5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tipemobil</value>
      <webElementGuid>04a2e9c4-0e92-4e1e-b7c2-e335bfc3038f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipe_mobil</value>
      <webElementGuid>5e320bad-289f-4ace-8497-945bccab57e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>6be321a3-37cb-4d4e-90f7-a684cd45806d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PilihSedanMinibusJeep</value>
      <webElementGuid>a8b5464a-60ba-4f6c-95a5-ee5e5b540ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipe_mobil&quot;)</value>
      <webElementGuid>d3b38e52-d6d3-432b-b9f1-592e24e8bdfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipe_mobil']</value>
      <webElementGuid>57443d63-2542-402d-ac74-cd531894907d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[2]/div[2]/p/select</value>
      <webElementGuid>8319c0d5-5a73-4f4f-a960-efe121e4007d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Mobil'])[1]/following::select[1]</value>
      <webElementGuid>7e90de25-4548-43dd-91ab-5080764de7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil Penumpang?'])[1]/following::select[2]</value>
      <webElementGuid>6d94b07f-e30b-496a-8dd0-5082669a608b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Mobil'])[1]/preceding::select[1]</value>
      <webElementGuid>8e4c5d56-ab7d-455d-bcc9-9da08f209322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usia Kendaraan(Rp)'])[1]/preceding::select[2]</value>
      <webElementGuid>4d2d628e-2c23-4da4-a3a2-403d1213285c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/p/select</value>
      <webElementGuid>c2c36ddd-998e-46fb-9ee1-edade7a8e3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tipemobil' and @id = 'tipe_mobil' and (text() = 'PilihSedanMinibusJeep' or . = 'PilihSedanMinibusJeep')]</value>
      <webElementGuid>bc3b2f91-3e9e-4467-8c96-11438e34565c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
