<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_10_Pilih Jenis Mobil</name>
   <tag></tag>
   <elementGuidId>e00352c6-5e31-4275-b07a-7da9bd454fc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jenis_mobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jenis_mobil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1f8d165f-8f80-4b92-be57-44450d228300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenismobil</value>
      <webElementGuid>59c0a3f0-58df-4ac5-8eef-2793b88b4c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenis_mobil</value>
      <webElementGuid>5ff4b694-a13b-4abd-93e7-75a110364870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>4fd1b917-6eb1-4f68-b57c-01b761ab4736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Pilih Jenis Mobil*
                                                    Baru
                                                    Bekas
                                                </value>
      <webElementGuid>cd012f46-0429-4e2c-9a52-f5b93bd7e866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenis_mobil&quot;)</value>
      <webElementGuid>2c73d739-664f-4c60-8bdd-b8dce80ea056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jenis_mobil']</value>
      <webElementGuid>59ecb0e6-28af-4b18-9735-6778403aff65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[3]/div[2]/p/select</value>
      <webElementGuid>99d291ba-3dd6-4501-be98-2901a6a69816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Mobil'])[1]/following::select[1]</value>
      <webElementGuid>f12ce612-78c5-4575-9063-a927d4043bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Mobil'])[1]/following::select[2]</value>
      <webElementGuid>ec7418a3-5e88-4abb-9e5b-b057437738ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usia Kendaraan(Rp)'])[1]/preceding::select[1]</value>
      <webElementGuid>a2534e19-64fa-41ef-876d-07cc9da86cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga(Rp)'])[1]/preceding::select[1]</value>
      <webElementGuid>cde16bff-d88c-4e34-9089-ef3acca505ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/p/select</value>
      <webElementGuid>567157bc-1a6f-4ebd-bd5a-b4d3f3df0b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jenismobil' and @id = 'jenis_mobil' and (text() = '
                                                    Pilih Jenis Mobil*
                                                    Baru
                                                    Bekas
                                                ' or . = '
                                                    Pilih Jenis Mobil*
                                                    Baru
                                                    Bekas
                                                ')]</value>
      <webElementGuid>84483d86-976d-4353-b24f-ee46a32c32c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
