<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_12_input Uang Muka(Rp)</name>
   <tag></tag>
   <elementGuidId>38237e59-7dcf-4e05-866c-655d73cecab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uang_muka</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uang_muka']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e56fc8d-468e-4257-bc7e-7ec03b7123d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dea2e244-033d-4093-bff5-24445240203e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>82524797-ac9b-414b-9f8e-ca31284c1a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uangmuka</value>
      <webElementGuid>5f390af8-bd83-4231-bafe-e2ff6448c31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uang_muka</value>
      <webElementGuid>e05f6b21-9ada-4620-b905-0d0f871b930e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Uang Muka*</value>
      <webElementGuid>fb5055fa-e72c-41f8-93a1-663755f3245f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uang_muka&quot;)</value>
      <webElementGuid>a4c25739-44c1-4830-92ab-1bb40c0ddae5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uang_muka']</value>
      <webElementGuid>d20e7707-9ff8-4675-bd92-6a6d06e266b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[6]/div[2]/p/input</value>
      <webElementGuid>a813f363-8f93-4d6e-965f-0361b8fade30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/p/input</value>
      <webElementGuid>c97fe38d-45df-41fd-8c4f-00814cfe83c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'uangmuka' and @id = 'uang_muka' and @placeholder = 'Uang Muka*']</value>
      <webElementGuid>1ee14a51-1c6b-48c7-afdb-56de8a32c9ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
