<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_14_Pilih Wilayah</name>
   <tag></tag>
   <elementGuidId>9799d384-2de1-48e8-939e-dedc38aa90cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wilayah</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='wilayah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9be79a65-1f77-4853-8e2f-b688936e349e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wilayah</value>
      <webElementGuid>eb6dc438-8d0e-4217-91f5-4c1aa9be58be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wilayah</value>
      <webElementGuid>16b95b7c-982a-4abd-bcdf-d47d9e527724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>9ade34fb-b5f3-4870-bba2-1c3b57578ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Pilih WilayahWilayah 1(Sumatera dan kepulauan di sekitarnya)Wilayah 2(DKI Jakarta, Banten, Jawa Barat)Wilayah 3(Selain Wilayah 1 dan 2)                                                </value>
      <webElementGuid>2f099c04-fc88-4684-9d2e-0a0c48a7037a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wilayah&quot;)</value>
      <webElementGuid>1191c504-f3fe-4fcb-86f9-0be0a7249f75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='wilayah']</value>
      <webElementGuid>659784d8-4c50-482b-8b9c-e80717fac879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[8]/div[2]/p/select</value>
      <webElementGuid>01d004ec-1fee-4465-af8b-c91439f31418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wilayah Asuransi'])[1]/following::select[1]</value>
      <webElementGuid>16f0c33f-839e-4101-b381-6b42869614a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangka Waktu Kredit (Bulan)'])[1]/following::select[2]</value>
      <webElementGuid>02749bcb-c1c0-4fbf-9aef-39cbb3248ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Syarat dan ketentuan yang berlaku'])[1]/preceding::select[1]</value>
      <webElementGuid>d507b2b8-0925-4419-b4db-391b8f8f03f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/preceding::select[1]</value>
      <webElementGuid>edf42ce2-2dfb-4efc-a3ac-d70dd2e9e496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/p/select</value>
      <webElementGuid>2d84210e-9277-4b78-854a-4fbf194947a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'wilayah' and @id = 'wilayah' and (text() = '
                                                    Pilih WilayahWilayah 1(Sumatera dan kepulauan di sekitarnya)Wilayah 2(DKI Jakarta, Banten, Jawa Barat)Wilayah 3(Selain Wilayah 1 dan 2)                                                ' or . = '
                                                    Pilih WilayahWilayah 1(Sumatera dan kepulauan di sekitarnya)Wilayah 2(DKI Jakarta, Banten, Jawa Barat)Wilayah 3(Selain Wilayah 1 dan 2)                                                ')]</value>
      <webElementGuid>6360a2ba-87ba-41e8-9391-28838b0652cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
