<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_11_input Harga(Rp)</name>
   <tag></tag>
   <elementGuidId>dd6a0bb5-c433-4fe9-8d7d-be7cce84441e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#harga_mobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='harga_mobil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70b38806-9bfd-4322-97b0-590666480317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81133a64-fc9f-4af9-9369-cae0f82321b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>a0f5c7ee-79fb-49ad-9038-c0f9a5b49018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>harga</value>
      <webElementGuid>ed6586e4-3968-41ae-9112-537ed942769d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>harga_mobil</value>
      <webElementGuid>4cf40d22-dde1-498e-a008-3c2673c82552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:if (isNaN(this.value)){this.value=0;};</value>
      <webElementGuid>8bebdc5b-71e5-4be8-830d-1da1725d6a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Harga*</value>
      <webElementGuid>f92d9a6c-0399-45d4-9723-9843079532c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;harga_mobil&quot;)</value>
      <webElementGuid>a22928f1-0d60-4371-bfba-1bb8c566cd05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='harga_mobil']</value>
      <webElementGuid>f5fe9f28-e0ca-4f5d-9b0a-6937785e6e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[5]/div[2]/p/input</value>
      <webElementGuid>fc5afd63-7d58-4fb5-94e5-e02af5677f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/p/input</value>
      <webElementGuid>f1976234-9a83-4b85-97a3-b39ed12f6f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'harga' and @id = 'harga_mobil' and @placeholder = 'Harga*']</value>
      <webElementGuid>97b5be94-abb8-4bc9-baf0-cc6e3a3708c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
