<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_29_input Pekerjaan</name>
   <tag></tag>
   <elementGuidId>940db754-91f9-491a-b8a5-638646939c3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kerja</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kerja']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9ef3e98-5f6b-470a-b055-e2cda24dd514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74e99914-8fdf-47fc-bbb8-6fc7b92f7474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>e5c1977c-b3bf-42f5-b7d0-28ecd0371b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kerja</value>
      <webElementGuid>ab8ffe01-2e47-4d02-a97e-4ed2fe08033f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kerja</value>
      <webElementGuid>7c1e4073-838f-4be7-b1cf-1da3d35ced4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pekerjaan</value>
      <webElementGuid>c4ab13f7-5106-4840-9050-7432a25e0839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kerja&quot;)</value>
      <webElementGuid>f845adfd-e6bc-413f-a3fd-12905ab7f20c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kerja']</value>
      <webElementGuid>47b11c93-6b0a-4b04-a994-ac900842f147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[9]/div[2]/p/input</value>
      <webElementGuid>27309606-bf19-41dd-8f2a-7c1a8a4522a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/p/input</value>
      <webElementGuid>ff6cda65-5023-4fc8-8a09-c2c136df60dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'kerja' and @id = 'kerja' and @placeholder = 'Pekerjaan']</value>
      <webElementGuid>7644721e-0566-4a44-bda3-00c9da03e773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
