<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_25_input Nomor Kartu Identitas</name>
   <tag></tag>
   <elementGuidId>10625112-a656-4c9e-908c-20742a21194a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nokartu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nokartu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3baa47d-d877-47b2-bfcc-8fb18eef6a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>341f7137-67e1-4de8-a3e6-00352fc2cc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>626c24aa-517a-42c2-9a4b-2081af5854e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nokartu</value>
      <webElementGuid>9bdc7a61-4d32-493b-8871-66e0546e5ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nokartu</value>
      <webElementGuid>8507bfd7-a6c5-471e-9e4e-b3a3ff7588d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Kartu Identitas*</value>
      <webElementGuid>1989eb6e-7786-49f2-9fa6-befac929d8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nokartu&quot;)</value>
      <webElementGuid>a96f6477-0ead-487b-bd4f-b9402cd659df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nokartu']</value>
      <webElementGuid>0bb50331-f19f-4399-b312-9885d931a0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[4]/div[2]/p/input</value>
      <webElementGuid>cd341a46-9e7d-4a4d-81fe-8f45e0cefdfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/p/input</value>
      <webElementGuid>af7b0f08-075b-41b9-985a-aac2498ddcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nokartu' and @id = 'nokartu' and @placeholder = 'Nomor Kartu Identitas*']</value>
      <webElementGuid>435d9c7f-b1e3-490f-bda0-2b3dc957195e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
