<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_40_txt Alamat sesuai NPWP_AS</name>
   <tag></tag>
   <elementGuidId>bd193328-9a4c-414c-b2d3-c9ce5ef10205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alamat_npwp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='alamat_npwp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f3e7d6f5-f878-4903-8c13-4e532617a7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat_npwp</value>
      <webElementGuid>1998e180-0b91-4c86-bda3-f92055862cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alamat_npwp</value>
      <webElementGuid>e8ede72d-f343-44d0-bc36-90f468f63298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e59c89d8-71aa-4bd1-9b7a-3616bad24fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>9c619ea6-d172-44fd-9578-114d89180a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alamat sesuai NPWP</value>
      <webElementGuid>23c32976-a921-411f-aa73-891b82122fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>735912c5-1f41-4a3d-addb-e7397739974b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a21846ee-d119-418a-b087-2ec76b22141d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alamat_npwp&quot;)</value>
      <webElementGuid>d6977347-7c4a-42ef-8d6b-74b2af5770d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='alamat_npwp']</value>
      <webElementGuid>f30e3fd9-71c2-4659-b9b0-f9808724a8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alamat_npwp_row']/div[2]/p/textarea</value>
      <webElementGuid>be60f31c-d424-4abd-9945-ad0c98c20306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/p/textarea</value>
      <webElementGuid>c9782520-7207-4211-afa4-9265a8f58d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'alamat_npwp' and @id = 'alamat_npwp' and @placeholder = 'Alamat sesuai NPWP']</value>
      <webElementGuid>8464a987-46fd-47f6-87dd-7907a7c32722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
