<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_27_input No Telepon</name>
   <tag></tag>
   <elementGuidId>8547200f-3adc-4949-8e7f-e0cf31fa2662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#no_telp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no_telp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8284558-d657-4a62-87d7-44376a8d8448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be3021cf-9af4-454e-b3d2-938fedaf6103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>d759047f-56e5-43a3-a597-5c27fa93ccb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_telp</value>
      <webElementGuid>eb1d047f-23b6-4a5f-abea-a99f6bcc87b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_telp</value>
      <webElementGuid>f32128e8-feff-4b09-85ae-41106762084e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Telepon*</value>
      <webElementGuid>74b0710a-9928-49ed-8e8d-43c4617de1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_telp&quot;)</value>
      <webElementGuid>693a994a-ff70-4d48-b64c-bfa0a2cea78f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no_telp']</value>
      <webElementGuid>efccd25e-453a-4f4b-adfb-33a8322a810b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[6]/div[2]/p/input</value>
      <webElementGuid>a7a4fee0-7611-4e86-96fc-ee4293656e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/p/input</value>
      <webElementGuid>5005a76f-3e75-4575-8a8c-d8f2c4c3ce32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'no_telp' and @id = 'no_telp' and @placeholder = 'No Telepon*']</value>
      <webElementGuid>06ccf20f-f7c4-49ea-bb96-030a841aa3f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
