<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_13_Pilih Tenor</name>
   <tag></tag>
   <elementGuidId>583fc0e1-b339-47e6-afbd-9af3214e56ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jangka_kredit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jangka_kredit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>61050638-cfd6-448a-9557-1fbe000f426c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jangkakredit</value>
      <webElementGuid>be82183e-36a0-40d2-bec9-a475d4355f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jangka_kredit</value>
      <webElementGuid>bb36062f-7622-49e7-868e-8b6e23034e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>8327eea8-8407-4c27-9cd5-125654ee138d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Tenor12243648</value>
      <webElementGuid>5b66a54f-2134-46eb-ba7b-1f2f629fd726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jangka_kredit&quot;)</value>
      <webElementGuid>25a1eaec-68ae-4df7-9839-8f9074fbe224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jangka_kredit']</value>
      <webElementGuid>7be27631-de12-488c-aac2-05fd25a5c18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[7]/div[2]/p/select</value>
      <webElementGuid>ac97936a-38f9-4d2e-94ae-a875f1067382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangka Waktu Kredit (Bulan)'])[1]/following::select[1]</value>
      <webElementGuid>41946026-171b-4943-b08b-372c7ea3c039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uang Muka(Rp)'])[1]/following::select[1]</value>
      <webElementGuid>f2f36086-e59c-453c-9b11-06db58d54352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wilayah Asuransi'])[1]/preceding::select[1]</value>
      <webElementGuid>070afbbd-fffe-4769-99a0-908bf7d9767e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Syarat dan ketentuan yang berlaku'])[1]/preceding::select[2]</value>
      <webElementGuid>35f852a8-1c9b-4f14-b667-341d256f11d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/p/select</value>
      <webElementGuid>11966114-bc87-4bd5-9f88-95a8bbe65d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jangkakredit' and @id = 'jangka_kredit' and (text() = 'Pilih Tenor12243648' or . = 'Pilih Tenor12243648')]</value>
      <webElementGuid>810f30ba-0fcf-4c73-b23a-0945554ca7ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
