<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_08_Pilih Mobil Penumpang</name>
   <tag></tag>
   <elementGuidId>8e290dc3-df5b-44a4-a72c-9dc989e3ad04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobil_penumpang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='mobil_penumpang']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c35aba17-b8a0-4f02-b96c-f1b5aaf1a676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobilpenumpang</value>
      <webElementGuid>51eb7c2f-2743-4062-9188-cb6c73739bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobil_penumpang</value>
      <webElementGuid>bb959105-4992-479d-a615-bfdd4b6630f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>27e306d7-5dc1-4cc1-b2b8-3b2717747057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Pilih*
                                                    Ya
                                                    Tidak
                                                </value>
      <webElementGuid>f08b7dd1-de4d-45aa-88c6-c69421bd4dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobil_penumpang&quot;)</value>
      <webElementGuid>a8590fb2-b923-451f-939d-41a30d66dfc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='mobil_penumpang']</value>
      <webElementGuid>749fa96f-24bd-4330-9ccf-d98b67bb55c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div/div[2]/p/select</value>
      <webElementGuid>73cf72b7-e342-4682-bacf-1373c9ab4285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil Penumpang?'])[1]/following::select[1]</value>
      <webElementGuid>71db554f-213b-42cd-85ae-fbbbce9e1243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simulasi Untuk Menghitung Angsuran Per Bulan'])[1]/following::select[1]</value>
      <webElementGuid>c856472a-4683-4215-bc06-ff4edc4ea5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Mobil'])[1]/preceding::select[1]</value>
      <webElementGuid>9c95cede-158b-473a-94d0-342a92853607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Mobil'])[1]/preceding::select[2]</value>
      <webElementGuid>c783cb7b-078d-442e-934b-cbd3d072a595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3e508188-41c4-48ea-a393-c37768bfbf0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'mobilpenumpang' and @id = 'mobil_penumpang' and (text() = '
                                                    Pilih*
                                                    Ya
                                                    Tidak
                                                ' or . = '
                                                    Pilih*
                                                    Ya
                                                    Tidak
                                                ')]</value>
      <webElementGuid>43ef1bae-12cb-465e-88df-62aefcf3df10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
