<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Harga(Rp)_harga</name>
   <tag></tag>
   <elementGuidId>b7527b86-6bcd-49bd-92e2-7f66633427f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='harga_mobil']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#harga_mobil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89beea3e-a734-47b6-9be6-84a120c0416e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10f0accb-47b3-4d08-bb09-474041fb6a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>3c80f6bc-60e6-429e-9395-6b098a7e4993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>harga</value>
      <webElementGuid>8c5a4b8c-8bc8-4eea-987f-7700cb6b890b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>harga_mobil</value>
      <webElementGuid>81d258fe-fc5a-4171-b11e-9f39e368927a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:if (isNaN(this.value)){this.value=0;};</value>
      <webElementGuid>943c0b3c-727d-4342-a0f3-ba1ace6c3c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Harga*</value>
      <webElementGuid>1454cfab-fc4c-47e2-ba95-d8f7deda0660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;harga_mobil&quot;)</value>
      <webElementGuid>d5966d8a-71f6-4835-b547-3bf5bb891f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='harga_mobil']</value>
      <webElementGuid>8683b7be-d9c5-4e42-8ea9-438c03219602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[5]/div[2]/p/input</value>
      <webElementGuid>c176e589-8d63-4b53-b424-646de14704eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/p/input</value>
      <webElementGuid>cc5737f4-dae7-4060-b9a2-e5bd9108a8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'harga' and @id = 'harga_mobil' and @placeholder = 'Harga*']</value>
      <webElementGuid>b98a34f3-cdae-47ca-be78-db50fb9049f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
