<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Uang Muka(Rp)_uangmuka</name>
   <tag></tag>
   <elementGuidId>6491c353-13ef-40c5-a044-42b72aeae3bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uang_muka']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uang_muka</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c580545e-b954-4269-8bad-7237d08cab1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15f7a422-1ed4-4bf0-8425-a89252b5b116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>a70accf1-4034-4193-91a1-095d301bb73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uangmuka</value>
      <webElementGuid>e2858416-cced-420b-afc3-cfdb54cf60e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uang_muka</value>
      <webElementGuid>d607a087-c13b-4a7d-a583-7f39d21f7cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Uang Muka*</value>
      <webElementGuid>f080a851-97bf-4716-a352-b72cf114f9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uang_muka&quot;)</value>
      <webElementGuid>cc471bcd-aa23-4b20-85c1-e754e834bd6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uang_muka']</value>
      <webElementGuid>d9927407-226d-45d2-b4b4-0fb395a00a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[6]/div[2]/p/input</value>
      <webElementGuid>3039b74f-383a-4da4-9f46-5236bad61913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/p/input</value>
      <webElementGuid>8b9f05ac-99cd-4a56-b370-bf872af611fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'uangmuka' and @id = 'uang_muka' and @placeholder = 'Uang Muka*']</value>
      <webElementGuid>1ecfa149-2321-4be7-abd5-52586a689e9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
