<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PilihSedanMinibusJeep</name>
   <tag></tag>
   <elementGuidId>5e0ddfb1-b00a-4b18-b5ee-8c9db2c4ce22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipe_mobil']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipe_mobil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d4f1b59e-2b97-4efe-874f-f770682df6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tipemobil</value>
      <webElementGuid>733ff706-f54c-40a9-bb67-563062f57bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipe_mobil</value>
      <webElementGuid>ea4f159b-4f94-4998-886f-24ef7d07c3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>1d698ee1-ab74-4f5b-b5ee-2ac97848bf65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PilihSedanMinibusJeep</value>
      <webElementGuid>a7071c55-fdbe-4ff7-80ce-1753847515cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipe_mobil&quot;)</value>
      <webElementGuid>914f598a-b144-46b2-808b-23edac9d981b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipe_mobil']</value>
      <webElementGuid>c1d1578e-d74a-4dd9-9a0e-a6faa3bb565c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[2]/div[2]/p/select</value>
      <webElementGuid>b274c6f5-3508-479a-a02a-404de839f8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Mobil'])[1]/following::select[1]</value>
      <webElementGuid>16fd3f69-c026-4189-8c47-09876315e30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil Penumpang?'])[1]/following::select[2]</value>
      <webElementGuid>db0439bb-30b9-4fed-96ff-86434cfb690f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Mobil'])[1]/preceding::select[1]</value>
      <webElementGuid>3fbe89c8-9969-48a3-a26d-6066f969004c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usia Kendaraan(Rp)'])[1]/preceding::select[2]</value>
      <webElementGuid>d6c6e78b-bc4b-41e5-9d5f-8640c98e637c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/p/select</value>
      <webElementGuid>ef373b8f-6df5-471a-aacd-41b7fc8e878a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tipemobil' and @id = 'tipe_mobil' and (text() = 'PilihSedanMinibusJeep' or . = 'PilihSedanMinibusJeep')]</value>
      <webElementGuid>59ccffd3-4075-41c2-816a-6a29618cf552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
