<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Jenis Mobil                   _9450ef</name>
   <tag></tag>
   <elementGuidId>7d0b16bc-b107-4152-bfb4-bd53329c6471</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jenis_mobil']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jenis_mobil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d8262bcf-6f4d-407c-8ae3-96bc3aacdd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenismobil</value>
      <webElementGuid>53732b13-43ad-4367-b22e-26b507382881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenis_mobil</value>
      <webElementGuid>b65d4202-f3d9-4e1f-abd8-5a6a7751f279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>da70601d-8888-4f29-8aac-a0e693a92755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Pilih Jenis Mobil*
                                                    Baru
                                                    Bekas
                                                </value>
      <webElementGuid>8a1c7be9-dd49-4da3-bbd0-fd6ce7959bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenis_mobil&quot;)</value>
      <webElementGuid>e061cee9-6f80-4102-8192-ae85b2918524</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jenis_mobil']</value>
      <webElementGuid>e3141254-6892-48fb-bc75-aad1d0926f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[3]/div[2]/p/select</value>
      <webElementGuid>06206d95-e0f8-4df4-b2ec-0fbb0b535e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Mobil'])[1]/following::select[1]</value>
      <webElementGuid>bcf7977c-3a92-4b44-888e-b082a85c6d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Mobil'])[1]/following::select[2]</value>
      <webElementGuid>60f6ede3-d2c6-4179-9478-5f62397931a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usia Kendaraan(Rp)'])[1]/preceding::select[1]</value>
      <webElementGuid>475c5f17-5817-4082-854a-d152ca78e7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga(Rp)'])[1]/preceding::select[1]</value>
      <webElementGuid>d044cec2-785e-448d-9c97-62af941ae5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/p/select</value>
      <webElementGuid>61cb47fc-69c7-4908-97ca-a8c2b91f10d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jenismobil' and @id = 'jenis_mobil' and (text() = '
                                                    Pilih Jenis Mobil*
                                                    Baru
                                                    Bekas
                                                ' or . = '
                                                    Pilih Jenis Mobil*
                                                    Baru
                                                    Bekas
                                                ')]</value>
      <webElementGuid>fa3b1063-48e4-4b7b-a876-e8fa5e1fae13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
