<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Tenor12243648</name>
   <tag></tag>
   <elementGuidId>25f454f0-3080-4073-b947-55158c61c1f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jangka_kredit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jangka_kredit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4bde114f-0529-4086-b2a8-6a59474898c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jangkakredit</value>
      <webElementGuid>d23095f6-804b-4ea3-b748-48076bd3d543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jangka_kredit</value>
      <webElementGuid>076174c8-336e-450a-8096-3b4bd8dae1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>5b11355d-7d9b-4155-b3e6-11fbeaff7917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Tenor12243648</value>
      <webElementGuid>31b80adf-1eb9-40db-8249-f831f22c2c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jangka_kredit&quot;)</value>
      <webElementGuid>03f11fa9-9290-42b3-b58f-c6baebdf5e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jangka_kredit']</value>
      <webElementGuid>c7b5df30-6ae0-4f90-84ba-d1fe78e379a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[7]/div[2]/p/select</value>
      <webElementGuid>51c91a0e-d7c7-4b6b-a6ec-5146ddbfc5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangka Waktu Kredit (Bulan)'])[1]/following::select[1]</value>
      <webElementGuid>7822be5b-5bd3-4265-8e82-94c1f7141e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uang Muka(Rp)'])[1]/following::select[1]</value>
      <webElementGuid>29a92fd2-a818-458a-ae72-0f4c984bcc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wilayah Asuransi'])[1]/preceding::select[1]</value>
      <webElementGuid>eeb88226-a357-4d10-8b20-696f40cc42b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Syarat dan ketentuan yang berlaku'])[1]/preceding::select[2]</value>
      <webElementGuid>688a2f7d-f312-4499-9de6-8be2beba20ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/p/select</value>
      <webElementGuid>d4db0510-d640-4252-8c02-b31bd7111a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jangkakredit' and @id = 'jangka_kredit' and (text() = 'Pilih Tenor12243648' or . = 'Pilih Tenor12243648')]</value>
      <webElementGuid>8946df53-3ad8-4964-a8da-176950567e42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
