<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih                               _5f2a32</name>
   <tag></tag>
   <elementGuidId>cd2c1d8d-cbb1-41e5-8bbd-9e4c68ec1265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='mobil_penumpang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mobil_penumpang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bee29f5c-4d8a-45d4-bddf-95fbe5b79779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobilpenumpang</value>
      <webElementGuid>ebb82edb-67cf-446a-a5a5-9cb07334fe59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobil_penumpang</value>
      <webElementGuid>d3a6d026-61a0-444a-92e0-9876e8e297ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>14ed2d54-43c6-4d76-bc0c-37a7c0af4432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Pilih*
                                                    Ya
                                                    Tidak
                                                </value>
      <webElementGuid>2039847f-9c3e-4e86-87aa-b02b7f3b63a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobil_penumpang&quot;)</value>
      <webElementGuid>45bda536-65d6-48a4-91d8-912a0770290f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='mobil_penumpang']</value>
      <webElementGuid>971a8045-d501-4592-86f7-9a50ee14958e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div/div[2]/p/select</value>
      <webElementGuid>aa6c23e1-5b9e-4f08-a7c1-6de433609d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil Penumpang?'])[1]/following::select[1]</value>
      <webElementGuid>c82bc754-a234-408e-9724-817b50c9052b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simulasi Untuk Menghitung Angsuran Per Bulan'])[1]/following::select[1]</value>
      <webElementGuid>c97078a8-9787-4d7d-973a-22a60007133f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Mobil'])[1]/preceding::select[1]</value>
      <webElementGuid>de0de675-b695-4e4e-8d01-c79ad782d56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Mobil'])[1]/preceding::select[2]</value>
      <webElementGuid>27c056c4-abf2-410c-947a-d6aa840ea258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f95ebe76-288e-4bfc-94e1-f58ac89feeae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'mobilpenumpang' and @id = 'mobil_penumpang' and (text() = '
                                                    Pilih*
                                                    Ya
                                                    Tidak
                                                ' or . = '
                                                    Pilih*
                                                    Ya
                                                    Tidak
                                                ')]</value>
      <webElementGuid>29aea5ba-b3d3-499f-901b-c86d990be5e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
