<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_06_Ringkasan Informasi Produk dan Layanan Ve_100725</name>
   <tag></tag>
   <elementGuidId>bafc36da-1aae-4efa-8402-10cc1a9f55e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li[5]/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.sfHover > ul > li.sfHover > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>20efbf3c-619f-4561-9781-9bc23d0eee56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mitsuilease.co.id/ripl</value>
      <webElementGuid>59ac3fb7-c088-48c5-8c73-3eb287dcd440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ringkasan Informasi Produk dan Layanan Versi Umum</value>
      <webElementGuid>2d9c854b-13ae-4fa6-b7b2-6505c00f4342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/ul[@id=&quot;main-menu&quot;]/li[@class=&quot;sfHover&quot;]/ul[1]/li[@class=&quot;sfHover&quot;]/a[1]</value>
      <webElementGuid>78db6b6c-a3ec-4d91-97e0-edf6302bb826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li[5]/ul/li[5]/a</value>
      <webElementGuid>9914dfca-5d6c-4e0f-9189-717bef8a9a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ringkasan Informasi Produk dan Layanan Versi Umum')]</value>
      <webElementGuid>3f99c52e-0f17-4dc1-9778-f09ddf23e3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lembaga Alternatif Penyelesaian Sengketa (LAPS)'])[1]/following::a[1]</value>
      <webElementGuid>ba771ab4-64f8-4365-be37-b1a28a212566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prosedur Pengaduan Konsumen'])[1]/following::a[2]</value>
      <webElementGuid>c8395fc9-4c07-4850-a60f-95d7ccb89dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KARIR'])[1]/preceding::a[1]</value>
      <webElementGuid>87d668cf-ed22-4d29-9605-fbf2f8c680c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/preceding::a[2]</value>
      <webElementGuid>c28f5477-2081-40c5-8624-d77c2bd9f199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ringkasan Informasi Produk dan Layanan Versi Umum']/parent::*</value>
      <webElementGuid>92049d82-ad6b-4443-bce6-089079abb547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mitsuilease.co.id/ripl')]</value>
      <webElementGuid>a017d714-f49d-4ca9-b43a-4a64e1ffa1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[5]/a</value>
      <webElementGuid>56709318-7f1e-4d29-9724-a359f6b95bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mitsuilease.co.id/ripl' and (text() = 'Ringkasan Informasi Produk dan Layanan Versi Umum' or . = 'Ringkasan Informasi Produk dan Layanan Versi Umum')]</value>
      <webElementGuid>9e89d810-15df-47ad-990d-7add2a7104f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
