<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_02_KomentarSaran</name>
   <tag></tag>
   <elementGuidId>6b80dd8d-5a75-4ac7-9489-c403c1dab0d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li[5]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.sfHover > ul > li.sfHover > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16f664e7-4093-45b8-ae5a-95fc003a95ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mitsuilease.co.id/komensaran</value>
      <webElementGuid>e03cbfa5-963e-4cf4-9acc-fd8bf973abfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Komentar/Saran</value>
      <webElementGuid>3484524d-3e3e-484f-9dab-fa00f606e96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/ul[@id=&quot;main-menu&quot;]/li[@class=&quot;sfHover&quot;]/ul[1]/li[@class=&quot;sfHover&quot;]/a[1]</value>
      <webElementGuid>984937ab-92f8-4f0a-9c9a-53b95558d49d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li[5]/ul/li/a</value>
      <webElementGuid>b61ec06d-1f83-47af-8033-703ff84a2793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Komentar/Saran')]</value>
      <webElementGuid>b49fb244-628c-4e5b-b57e-637fcd665b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulir Permohonan Pengecekan Data'])[1]/following::a[2]</value>
      <webElementGuid>af5d414a-9d8f-4dc9-acde-8a9ee828aae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Persyaratan Pengambilan BPKB'])[1]/following::a[3]</value>
      <webElementGuid>884f265c-206c-4208-b83a-913ff0774687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[1]</value>
      <webElementGuid>8767a494-088f-4baf-9b3f-42c5bed12ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prosedur Pengaduan Konsumen'])[1]/preceding::a[2]</value>
      <webElementGuid>cb7aa405-4f31-498c-82d7-68480e42fa85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Komentar/Saran']/parent::*</value>
      <webElementGuid>cc4740ef-7ea8-4e56-b4d9-8d2a80a187df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mitsuilease.co.id/komensaran')]</value>
      <webElementGuid>97ebb5a5-b815-4339-a98a-8d64ebc1a879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a</value>
      <webElementGuid>f82c22a4-44d1-427b-a23c-9f9d11370994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mitsuilease.co.id/komensaran' and (text() = 'Komentar/Saran' or . = 'Komentar/Saran')]</value>
      <webElementGuid>11998c60-f9dd-4e5c-9684-f5d0d98c1809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
