<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_05_input Komentar Saran message</name>
   <tag></tag>
   <elementGuidId>aeddc656-5651-40ba-ab7a-306450022c04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comment_message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='comment_message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dd969c80-d3ab-4bb4-bd94-8dc4b40f7ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>17655bce-b428-49af-9d30-a08c56c2997f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>88</value>
      <webElementGuid>74bd4787-d0db-4d52-8b1b-517a49af0b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comment_message</value>
      <webElementGuid>679e2d4b-5d8b-46aa-ae32-e0285bda2301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>c9f8fe87-6d07-4cb6-a58f-2949c9e6c02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pesan*</value>
      <webElementGuid>2a6cd4ab-e367-4510-9fbc-7bf3f082a540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment_message&quot;)</value>
      <webElementGuid>5606a76b-1411-4a70-8a48-774bb12cf966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='comment_message']</value>
      <webElementGuid>c96a1c96-57c7-44d1-95e1-cf3d63e58f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='bootstrapSelectForm']/div[2]/div/p/textarea</value>
      <webElementGuid>f0ddecab-a02e-4eee-a206-545759b95ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0c1892f1-05b2-4c86-a8d6-1465faaa6a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'comment_message' and @name = 'message' and @placeholder = 'Pesan*']</value>
      <webElementGuid>4ebe9052-8a45-4f79-8ebd-3b35da9c6c16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
