<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_04_input_Komentar Saran</name>
   <tag></tag>
   <elementGuidId>5e5929f6-dcd1-4c34-a456-b5e33deb94a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comment_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='comment_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24bec3d4-bbd0-41c9-9089-c181f0da37d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>000d00c5-5cf1-4924-ab9b-5b7e317003d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>d1af08bd-9b5f-4320-96cf-c80982327912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>207cd4a1-15fa-4467-96c7-e7f89d737997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comment_email</value>
      <webElementGuid>738a1976-ef96-4d1e-bbc3-c154e2b5132a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email*</value>
      <webElementGuid>33417f78-d5c1-4271-9672-1a88db92746f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment_email&quot;)</value>
      <webElementGuid>47ff700e-5223-4bff-99a1-1dd09358a5b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='comment_email']</value>
      <webElementGuid>9f97f0aa-f47b-4554-9dd9-3ea750a53d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='bootstrapSelectForm']/div/div[2]/p/input</value>
      <webElementGuid>421ac773-c752-47b8-84c4-5fe5423389cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p/input</value>
      <webElementGuid>88fb9389-3e44-440a-8736-006b459c9ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email' and @id = 'comment_email' and @placeholder = 'Email*']</value>
      <webElementGuid>f19a515b-1ece-4af6-b6e5-8b15f0b26dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
