<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_03_input Komentar Saran name</name>
   <tag></tag>
   <elementGuidId>dcb1ffef-d320-4c32-9886-8bfacfbdbe54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comment_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='comment_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>282f9f9d-7e7d-46c0-985b-49857e8f1220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee1f52f3-9027-4a4c-8d57-351260dd2ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>b9cd5605-9d90-491d-bfee-915181005cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>76f36470-5977-4d18-961e-99021bf4fa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comment_name</value>
      <webElementGuid>9eced122-8ef2-4160-b0d7-a64cbacfadb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama*</value>
      <webElementGuid>87af0e2c-4ae3-4284-8a23-7cab9500bc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment_name&quot;)</value>
      <webElementGuid>2934cdd8-baac-4bf8-9b22-6d6d62c7eeef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='comment_name']</value>
      <webElementGuid>4a008e38-9ece-48ab-b4a1-a608f4748c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='bootstrapSelectForm']/div/div/p/input</value>
      <webElementGuid>4af5795d-e20b-4723-b09d-80a733fbaeba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p/input</value>
      <webElementGuid>aaf714ac-8121-456d-9a34-3891b47962d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'name' and @id = 'comment_name' and @placeholder = 'Nama*']</value>
      <webElementGuid>098a98e9-47d3-4f8b-80a2-0de31768dbeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
