<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Please tell us about yourself_dolphi_fa9299</name>
   <tag></tag>
   <elementGuidId>20db4b11-5d4d-4c06-940f-0578f6da031b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.dolphin-message-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0059193e-767f-4592-884e-333f418aee86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6360409-44c8-43fb-a0c2-73d31b111c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Minimize</value>
      <webElementGuid>754c50df-f94f-4ede-a25d-8f5d8fa2c201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dolphin-message-close</value>
      <webElementGuid>f33563b8-faa4-4fd8-963d-8fc9b1c27c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-close&quot;)/button[@class=&quot;dolphin-message-close&quot;]</value>
      <webElementGuid>65a16e5a-9544-44bd-b58b-ab37c21e0e09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>d7229c4a-1357-4e4a-a68f-ac5a052d0e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-close']/button</value>
      <webElementGuid>543c8052-a71a-4124-b869-78d4e1bc9621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please tell us about yourself'])[1]/following::button[1]</value>
      <webElementGuid>e0b72416-fa97-428d-b132-5e7650c4eee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Our Chat'])[1]/following::button[1]</value>
      <webElementGuid>1c2c3308-a173-45fe-8554-0dc37147b461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[3]/preceding::button[1]</value>
      <webElementGuid>8931b299-8587-438a-8d0e-fe85561ca242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[3]/button</value>
      <webElementGuid>c4c2be19-6e67-4f39-bba2-cbca3664873f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Minimize']</value>
      <webElementGuid>d6673e1e-779a-480c-b3bf-361317d03e4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
