<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Connect_dolphin-chat-icon</name>
   <tag></tag>
   <elementGuidId>91ec4326-dc91-44da-b279-94a0ceedeec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dolphin-chat-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dolphin-chat-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>755331c5-5fe1-4b5b-a602-74217a9173d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dolphin-chat-icon</value>
      <webElementGuid>bf3caf12-b6f5-4dbd-9b2a-fd88d80299a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dolphin-chat-icon</value>
      <webElementGuid>b3d4ea64-363f-4c19-be17-af49bdcc5194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dolphin-chat-icon&quot;)</value>
      <webElementGuid>f3b6bebe-58da-4e6c-94c8-d816c883897f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dolphin-chat-icon']</value>
      <webElementGuid>6db84612-9e08-4f34-810a-adfe0e21ca86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect'])[1]/following::div[3]</value>
      <webElementGuid>e3ae57d7-55c8-4dd8-9e84-d1270452039f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Åland Islands'])[1]/following::div[3]</value>
      <webElementGuid>c8e7d39b-3ad3-4c29-a89e-f9f290f9e72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]</value>
      <webElementGuid>065bd1df-c9e2-45c4-86d0-e03ce6211c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dolphin-chat-icon']</value>
      <webElementGuid>fcc8ce98-0dc1-4951-9242-4302c92b2f28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
