<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama PIC dari Pemohon_nama_pic</name>
   <tag></tag>
   <elementGuidId>fc49522c-d212-4cab-950c-82d2acb1fce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_pic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nama_pic</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0809c4c0-618b-4898-9ced-b3c1d232b78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_pic</value>
      <webElementGuid>a847b1f9-a6a8-4efe-a6b0-4c6b6d937384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_pic</value>
      <webElementGuid>dd2528d2-0575-4e08-b562-081120be3091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8cf078d7-24d8-4b37-8040-4ccc164aac41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama PIC dari Pemohon</value>
      <webElementGuid>3ecfe38c-04c1-410b-9f31-18a747913927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>309195f7-2d7d-445e-986c-c78fd79c1463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>39c5340b-dd6f-4796-ae78-4ce97caf3a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_pic&quot;)</value>
      <webElementGuid>f3f6e681-a2b4-4b11-8958-5ed37f120ef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_pic']</value>
      <webElementGuid>74f7959b-5c5b-48ce-bf70-91f70afbe476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nama_pic_row']/div[2]/p/input</value>
      <webElementGuid>1dd299e1-c89d-4801-8568-06fe534f0c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/p/input</value>
      <webElementGuid>0402c513-5ae5-429d-8b53-23b73b1c37cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_pic' and @id = 'nama_pic' and @type = 'text' and @placeholder = 'Nama PIC dari Pemohon']</value>
      <webElementGuid>b3631716-21f5-4317-91e6-24e125a8e6d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
