<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you have questions Come chat with _33a405</name>
   <tag></tag>
   <elementGuidId>5e200432-159a-447c-a15f-81c5465ae7e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dolphin-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dolphin-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdb1e992-9a54-4824-a38f-afaf31ce67b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dolphin-name</value>
      <webElementGuid>a0a5a59e-b359-464d-8427-82aabe654bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9efe1b8-8be7-4b9a-b261-51a4f44d94d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dolphin-name-input</value>
      <webElementGuid>826f004c-df78-42fd-aa74-1acbaa5da219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your name</value>
      <webElementGuid>d8709763-ef41-4437-9801-54d024eac77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dolphin-name&quot;)</value>
      <webElementGuid>62aa06e0-69be-4901-990c-617a92a8da5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dolphin-name']</value>
      <webElementGuid>98649e7d-0376-4ed8-9da7-dc490190fe44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dolphin-login-body']/input</value>
      <webElementGuid>e1137627-b18a-4787-a8c2-44f8e156ed57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please tell us about yourself'])[1]/following::input[1]</value>
      <webElementGuid>ec1cc8fe-5ed6-4f73-9b51-def3751e6596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[3]/preceding::input[1]</value>
      <webElementGuid>fee0f31d-12ba-425a-adbc-eae928cdec95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afghanistan (‫افغانستان‬‎)'])[1]/preceding::input[1]</value>
      <webElementGuid>a168a666-bd8d-4c72-8f25-33708ce83f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4004a0d5-cb2f-4551-ad9e-5ce566736ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dolphin-name' and @type = 'text' and @placeholder = 'Enter your name']</value>
      <webElementGuid>991d1364-415e-4378-af49-2d8a5ad3493f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
