<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Kartu Identitas_nokartu</name>
   <tag></tag>
   <elementGuidId>0077859d-07be-48b7-9221-f9abb618a96e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nokartu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nokartu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>371fe07e-1e94-46b0-bbd3-0f01928d4683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1d6beef-d8f9-45cf-9f3e-90c01098fd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>bd24e21c-e098-49b1-82e4-7a757219a8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nokartu</value>
      <webElementGuid>72a6339e-d2da-4346-aca2-e1286ab960d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nokartu</value>
      <webElementGuid>071ac669-1c5f-40a8-8c8b-7c45810f78dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Kartu Identitas*</value>
      <webElementGuid>ff8236fa-f780-43a2-a364-d2bb693f24b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nokartu&quot;)</value>
      <webElementGuid>53205ba4-e44a-49b8-b8ba-951a5c65f5ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nokartu']</value>
      <webElementGuid>0b4b5736-cbf8-4d49-8099-4845912808c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[4]/div[2]/p/input</value>
      <webElementGuid>b06b8d2d-4392-4b21-907b-e883a016428b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/p/input</value>
      <webElementGuid>80dc6ed1-9cc2-4bf4-a669-1bccdce1ded9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nokartu' and @id = 'nokartu' and @placeholder = 'Nomor Kartu Identitas*']</value>
      <webElementGuid>259abb01-e770-4732-9a5f-1049def2733c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
