<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pekerjaan_kerja</name>
   <tag></tag>
   <elementGuidId>3bc5b5dd-f820-4ec6-86ae-00418066a8c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kerja']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kerja</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6218f17f-1cd3-482c-bccf-a6dbf4dc1a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>224755be-c3b1-4df7-9624-b09ab271bf78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>4131ba5e-464e-4011-84cb-5815e4ea35fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kerja</value>
      <webElementGuid>028532c4-7b51-4498-99b3-7d58c1c2b412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kerja</value>
      <webElementGuid>f2808b6f-8e75-4f65-a46c-3dfdba206b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pekerjaan</value>
      <webElementGuid>654fe1f4-ed0c-4380-a492-b95b49931c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kerja&quot;)</value>
      <webElementGuid>0e656cf1-9ca3-43fb-a745-688858388454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kerja']</value>
      <webElementGuid>2adddea0-a38d-46ab-86f8-27a08632e370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[9]/div[2]/p/input</value>
      <webElementGuid>a45ff850-709d-493e-8e45-04e1e603aaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/p/input</value>
      <webElementGuid>e94b0ed6-e16c-422a-b72d-40de71187282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'kerja' and @id = 'kerja' and @placeholder = 'Pekerjaan']</value>
      <webElementGuid>0a77f021-1d9a-49fe-b234-af48a54ee1c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
