<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Telepon_phone_npwp</name>
   <tag></tag>
   <elementGuidId>c6cf5f1f-28f9-4864-8d9e-b811292e10b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone_npwp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phone_npwp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bf632c6-de0c-41fa-90e4-ad3e3ab3762a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_npwp</value>
      <webElementGuid>0de64569-731e-4b7d-ad48-61a797b1ec0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone_npwp</value>
      <webElementGuid>9278c2f5-a6a0-4e69-93a9-b1fd2ecad40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92e6b74e-067c-44a8-9f44-e0feaa46437c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>format: 1234567890 (harus angka, min 9 digit)</value>
      <webElementGuid>bf89d3a4-be1d-48fe-85d6-152dacc6afa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>73fb38ef-354f-412e-af2b-c19506b20627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>75f4b618-0f50-4005-902c-23cb68815d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ac6e91eb-90ce-4aab-849e-6145ef595928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone_npwp&quot;)</value>
      <webElementGuid>f11825d1-be2a-4548-9f7b-ae886fd3bb70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone_npwp']</value>
      <webElementGuid>fed0f3fa-3209-4d34-9325-6585680e71b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='phone_npwp_row']/div[2]/p/input</value>
      <webElementGuid>a200d228-4c44-4fd4-9c86-82a886d0fbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/p/input</value>
      <webElementGuid>3806e1e8-2f33-40b9-a90c-b5b94bb79129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phone_npwp' and @id = 'phone_npwp' and @type = 'text' and @placeholder = 'format: 1234567890 (harus angka, min 9 digit)']</value>
      <webElementGuid>0a99973a-71d6-4fb7-856f-c0bffdd6a1ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
