<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_dolphin-email</name>
   <tag></tag>
   <elementGuidId>31e118a3-702b-4ddc-a2cf-4381b377c5ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dolphin-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dolphin-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c984ef8-4981-4382-9813-a843f763dc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dolphin-email</value>
      <webElementGuid>d6d37773-6df6-48ee-9be9-02ab471ad481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab40cc19-d3d4-4a19-bf56-9df68ac50919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dolphin-email-input</value>
      <webElementGuid>fbb91e2e-b2f1-4129-aa48-0fb8247db302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>596e3aa7-6932-4d11-90d0-05554233aa41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dolphin-email&quot;)</value>
      <webElementGuid>6a81aad0-8d65-4939-a7f8-8f08e236c5be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dolphin-email']</value>
      <webElementGuid>4963a66b-80d0-4df7-8e72-6a5ff829a828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dolphin-login-body']/input[2]</value>
      <webElementGuid>5756960d-23ac-48bd-99b5-ecd6b5c48c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Åland Islands'])[1]/following::input[2]</value>
      <webElementGuid>074c90a2-0fb4-4b1f-b046-caf94c9e5fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zimbabwe'])[1]/following::input[2]</value>
      <webElementGuid>64499250-a42e-48d9-ac73-5d598bc915e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect'])[1]/preceding::input[1]</value>
      <webElementGuid>6beeb8ee-aa74-4327-90dd-fa09dc81ec75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>2abe871b-29e2-45fa-85b2-2ca41d9941d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dolphin-email' and @type = 'text' and @placeholder = 'Enter your email']</value>
      <webElementGuid>697dd84e-5625-426b-b40e-a1df299d489d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
