<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jenis Kelamin_gender</name>
   <tag></tag>
   <elementGuidId>7760e2dc-13b4-4416-9ef0-838d955652b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='gender'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3de3d5da-41c0-4d99-b17f-60990b5ca4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d4c3e1d7-dcb5-4a16-a1f8-5832c19a95ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>0791e7b5-936c-43bc-af27-5aa254ed053c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Wanita</value>
      <webElementGuid>a47b0a74-318c-49fb-83a8-4ac5e8670126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form&quot;)/form[@class=&quot;contact-form clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9 col-sm-9&quot;]/p[@class=&quot;input-block&quot;]/input[2]</value>
      <webElementGuid>96417912-0f4c-4da5-8795-6e6b5b0cb5c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='gender'])[2]</value>
      <webElementGuid>ea082b79-f18d-45c1-ad59-3853f3b03e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[2]/div[2]/p/input[2]</value>
      <webElementGuid>c714ecaf-7f2f-4e7e-be31-317e83502056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input[2]</value>
      <webElementGuid>7f522ea7-36a3-407d-857c-8d9a9c64fb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'gender']</value>
      <webElementGuid>0907d305-a819-44ff-b9b2-5a3fc53ac00a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
