<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Jenis Mobil                   _9450ef</name>
   <tag></tag>
   <elementGuidId>69cea20e-bf4d-48a9-b6b8-decfadac97ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jenismobil']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jenismobil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>10104324-eca2-47c7-964b-dcdf48a12474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenismobil</value>
      <webElementGuid>878f9708-f587-4f33-b5f6-b2fabb6e8433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenismobil</value>
      <webElementGuid>eb9ed4fe-89e2-42f7-889d-770dac300f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>208f46db-c8ba-4f60-89b0-349062d27f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Pilih Jenis Mobil*
                                                    Baru
                                                    Bekas
                                                </value>
      <webElementGuid>8b791b78-37c5-4106-9c32-e17ccc9dca0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenismobil&quot;)</value>
      <webElementGuid>dac7caf1-96bc-41e4-8cb9-3f6ad49c4035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jenismobil']</value>
      <webElementGuid>bac3b09d-e22f-4b85-816f-26a3f5f9f34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[10]/div[2]/p/select</value>
      <webElementGuid>73ed2844-e9b5-43eb-acb3-6bfcb6fa7f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Mobil'])[1]/following::select[1]</value>
      <webElementGuid>e493ffae-21bf-4031-a8ac-4669d3842149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pekerjaan'])[1]/following::select[1]</value>
      <webElementGuid>7333b4d4-4a5c-4123-aec2-04663923d842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merk Mobil'])[1]/preceding::select[1]</value>
      <webElementGuid>55535bff-f9b7-4e9d-8171-e8c14fbd197b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model Mobil'])[1]/preceding::select[2]</value>
      <webElementGuid>53757679-01fe-4b0f-bfdb-5c8d6ee916e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/p/select</value>
      <webElementGuid>30747976-114a-4062-9506-23d53e0803c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jenismobil' and @id = 'jenismobil' and (text() = '
                                                    Pilih Jenis Mobil*
                                                    Baru
                                                    Bekas
                                                ' or . = '
                                                    Pilih Jenis Mobil*
                                                    Baru
                                                    Bekas
                                                ')]</value>
      <webElementGuid>e9d3109f-67bb-47d1-94d1-33fe821761e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
