<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Tipe MobilMT</name>
   <tag></tag>
   <elementGuidId>f8dc858b-6bf6-484a-9c69-2d3be2bbdfaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipemobil']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipemobil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e6b474d8-ea26-4b1a-b85f-a2c7aaf7e26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tipemobil</value>
      <webElementGuid>23669fec-2368-4b04-8ebb-74465983b5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipemobil</value>
      <webElementGuid>fdc6e26d-cf18-430a-b5a5-6f690045c9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>5ea927aa-0e1c-47ca-aa64-5e5bb9083662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Tipe Mobil*M/T</value>
      <webElementGuid>9c9a168c-49e0-404e-84a9-ea70c63d3310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipemobil&quot;)</value>
      <webElementGuid>c5e302c5-e168-45e7-b338-dcf5b4eef233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipemobil']</value>
      <webElementGuid>7d9f579a-26ec-4e6e-9d4d-36a338b04c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[13]/div[2]/p/select</value>
      <webElementGuid>9f91f560-388f-497b-8fee-f71d2ebe224a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Mobil'])[1]/following::select[1]</value>
      <webElementGuid>78ef0249-6252-4d0d-8cbb-151f62f6ef30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model Mobil'])[1]/following::select[2]</value>
      <webElementGuid>be7dcc53-d257-4a55-b794-a5edd2ed3e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[2]/preceding::select[1]</value>
      <webElementGuid>b964c2e3-4f68-42eb-9a48-2175fe4952f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROFIL'])[3]/preceding::select[1]</value>
      <webElementGuid>92477a69-54dd-4a43-a5e9-5cc6ab4f2b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/p/select</value>
      <webElementGuid>4c61cd23-20b6-42ab-8cf9-e6bf64d9564f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tipemobil' and @id = 'tipemobil' and (text() = 'Pilih Tipe Mobil*M/T' or . = 'Pilih Tipe Mobil*M/T')]</value>
      <webElementGuid>b3f4b2ab-b418-4424-b048-22e8d40ab0f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
