<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Kartu Identitas               _7680ec</name>
   <tag></tag>
   <elementGuidId>618e7763-e21e-4ec0-8cac-668989fb7b7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='kartu_pribadi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kartu_pribadi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>275caf31-7223-429d-a1f9-954b3c79d2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kartu_pribadi</value>
      <webElementGuid>57d898c3-ec4a-42fb-8deb-ad5ce263761d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kartu_pribadi</value>
      <webElementGuid>4f7994fc-b2df-4c68-8f62-9338d2b751a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>6eaca6f0-5eb3-4f57-985a-a17c63eee26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Pilih Kartu Identitas
                                                    KTP
                                                    SIM
                                                    PASPOR
                                                </value>
      <webElementGuid>bc023b75-a37d-460e-bb50-4f1d5180412d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kartu_pribadi&quot;)</value>
      <webElementGuid>583cd5ea-278c-49e7-b9eb-d7730249d331</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='kartu_pribadi']</value>
      <webElementGuid>33405b2d-7684-48a1-8528-5852aabfe0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[3]/div[2]/p/select</value>
      <webElementGuid>559b337d-4552-45ab-90d8-efdc89496c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kartu Identitas'])[1]/following::select[1]</value>
      <webElementGuid>c2589887-e322-4df9-b216-116517b4326d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kelamin'])[1]/following::select[1]</value>
      <webElementGuid>39852370-73e0-4a2c-9465-3ec1836c7106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Kartu Identitas'])[1]/preceding::select[1]</value>
      <webElementGuid>7352be6d-063d-4f92-89e7-336a459205c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::select[1]</value>
      <webElementGuid>fcd95289-6811-4b17-aac8-1cb4b55f74ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f59de465-fcbf-4f6f-9aaa-012b64515674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kartu_pribadi' and @id = 'kartu_pribadi' and (text() = '
                                                    Pilih Kartu Identitas
                                                    KTP
                                                    SIM
                                                    PASPOR
                                                ' or . = '
                                                    Pilih Kartu Identitas
                                                    KTP
                                                    SIM
                                                    PASPOR
                                                ')]</value>
      <webElementGuid>2e63699c-1f34-4772-8fd4-11c43278befe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
