<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat_alamat</name>
   <tag></tag>
   <elementGuidId>f83bdf0c-7351-455d-a08f-57df69c86e8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='alamat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alamat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7bc9915e-d5cf-4e68-a9e4-d4431f7cd20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a1ed5f5e-24e9-4a16-905b-789478c402b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>88</value>
      <webElementGuid>1810a5ab-8f15-446f-9214-93bf95a7c782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alamat</value>
      <webElementGuid>e0443b3a-a703-4e9c-8434-e508963e33dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat</value>
      <webElementGuid>cf16c292-4515-45c1-ba76-da2f736574d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alamat*</value>
      <webElementGuid>a992dd0b-ee8c-4ff7-8793-4bade766882e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alamat&quot;)</value>
      <webElementGuid>63e0712f-b25d-419e-b6c6-c43fd460f8b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='alamat']</value>
      <webElementGuid>ff5e7858-f1c2-4593-b48c-28aa5e167841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[8]/div[2]/p/textarea</value>
      <webElementGuid>f5691616-b51e-448a-8473-a88bd3521608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1b3bef4d-e554-456d-9b57-a3ed73b3c51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'alamat' and @name = 'alamat' and @placeholder = 'Alamat*']</value>
      <webElementGuid>972d50b5-7f29-4383-8753-b13e25db213d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
