<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_38_input Nama Pemohon Npwp_AS</name>
   <tag></tag>
   <elementGuidId>69a41655-f7dd-4735-bc0a-77810aebf301</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_pemohon_npwp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_pemohon_npwp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d3f45e0-13e9-4f3d-9895-7bab57d82184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_pemohon_npwp</value>
      <webElementGuid>f526fcd3-13a2-411d-b7a7-2ca803a7b827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_pemohon_npwp</value>
      <webElementGuid>7e37473f-f448-4ba3-8288-95ed5448027f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b579db51-c303-4d61-ae97-2d67ff3d25f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Pemohon</value>
      <webElementGuid>2b545766-deae-411a-afb2-e63ec2d210b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>32637647-8eaa-47b8-93c5-a9b4e100f369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>70aea1ce-e736-4c88-9d55-5ed68d706401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_pemohon_npwp&quot;)</value>
      <webElementGuid>72ec295d-46a3-4057-81b5-2bd90628b7fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_pemohon_npwp']</value>
      <webElementGuid>14704202-2c3d-4def-be97-6dad512cd3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nama_pemohon_npwp_row']/div[2]/p/input</value>
      <webElementGuid>a74da1ea-c27e-4a66-8436-bae6a2faa2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/p/input</value>
      <webElementGuid>62c2f261-2a8d-41cb-883c-98c10dd2ae5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_pemohon_npwp' and @id = 'nama_pemohon_npwp' and @type = 'text' and @placeholder = 'Nama Pemohon']</value>
      <webElementGuid>33b44737-67ba-4848-a1ec-70a7a286cb49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
