<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_39_input Nomor NPWP_AS</name>
   <tag></tag>
   <elementGuidId>988a5247-9605-4205-befa-4fedcaa9481c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#no_npwp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no_npwp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>453d01ae-b27e-4d1e-88ac-8135c5059de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_npwp</value>
      <webElementGuid>ba7aca71-9f43-4690-a054-d7f8cbe6a2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_npwp</value>
      <webElementGuid>569856fb-58d3-48de-b490-4eb771f02a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e978921b-1ed4-47c3-998f-4415793269df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor NPWP</value>
      <webElementGuid>b7e40004-56f2-41b6-b91a-7ab952b5f53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>60e22e3d-dd6d-402e-8f64-c25293db04a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>63c9d0b2-8dbd-4eab-98fa-e646494d5d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3c5b9548-9a27-406c-8f1e-86411d5576f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_npwp&quot;)</value>
      <webElementGuid>f86e3ba5-3b60-48df-964d-50f5c9e12dd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no_npwp']</value>
      <webElementGuid>bca8f4c8-d966-4804-85ca-cf10fe9f4b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='no_npwp_row']/div[2]/p/input</value>
      <webElementGuid>03c99679-5ffb-4f37-a463-529f8557daeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/p/input</value>
      <webElementGuid>90c8e9d1-a15a-4cb4-be14-86828d5e9840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'no_npwp' and @id = 'no_npwp' and @type = 'text' and @placeholder = 'Nomor NPWP']</value>
      <webElementGuid>6ce707d6-0d2a-4131-9e5c-31f7210fdd19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
