<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_33_Pilih Merk Mobil_AS</name>
   <tag></tag>
   <elementGuidId>e7ca5015-1a9a-477c-8930-56f2d821001f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#merkmobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='merkmobil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b7fc53ef-d0e3-4c91-9acb-c00977b4d273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>merkmobil</value>
      <webElementGuid>6097660b-33e3-44bf-ab00-c10c50ac0001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>merkmobil</value>
      <webElementGuid>cceadbed-c716-4f21-9c7f-ee5841f8a7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>c4ca584d-dbad-4d1a-831b-5011e4211f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Pilih Merk Mobil*
                                                                                                            AUDI
                                                                                                            BENTLEY
                                                                                                            BMW
                                                                                                            CHERY
                                                                                                            CHEVROLET
                                                                                                            CHRYSLER
                                                                                                            DAEWOO
                                                                                                            DAIHATSU
                                                                                                            DODGE
                                                                                                            FORD
                                                                                                            GEELY
                                                                                                            HONDA
                                                                                                            HYUNDAI
                                                                                                            INFINITI
                                                                                                            ISUZU
                                                                                                            JAGUAR
                                                                                                            JEEP
                                                                                                            KIA
                                                                                                            LAND ROVER
                                                                                                            LEXUS
                                                                                                            MAZDA
                                                                                                            MERCEDES
                                                                                                            MINI
                                                                                                            MITSUBISHI
                                                                                                            NISSAN
                                                                                                            PEUGEOT
                                                                                                            PORSCHE
                                                                                                            PROTON
                                                                                                            RENAULT
                                                                                                            SAAB
                                                                                                            SMART
                                                                                                            SSANGYONG
                                                                                                            SUBARU
                                                                                                            SUZUKI
                                                                                                            TOYOTA
                                                                                                            VOLKSWAGEN
                                                                                                            VOLVO
                                                                                                    </value>
      <webElementGuid>b34906d0-e41e-40f8-af69-a369818a9cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merkmobil&quot;)</value>
      <webElementGuid>0464c82f-5296-4ddd-ad0f-e95984eeb162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='merkmobil']</value>
      <webElementGuid>623f091a-fca8-4ad4-a48d-61e08579f5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[11]/div[2]/p/select</value>
      <webElementGuid>5336ae62-cb68-4ed0-af0d-c81e49f7dfdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merk Mobil'])[1]/following::select[1]</value>
      <webElementGuid>cc304d3e-13bd-4c8f-82af-445e18b092f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Mobil'])[1]/following::select[2]</value>
      <webElementGuid>bb6f0188-96a6-4f80-a09b-c240fab7711e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model Mobil'])[1]/preceding::select[1]</value>
      <webElementGuid>46bf68b3-0659-4375-93b7-eb4d88a6d475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Mobil'])[1]/preceding::select[2]</value>
      <webElementGuid>424f12a9-6094-4642-a6d5-aebedea555bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/p/select</value>
      <webElementGuid>bc41f86f-47bb-49f2-9b61-b770db66a92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'merkmobil' and @id = 'merkmobil' and (text() = '
                                                    Pilih Merk Mobil*
                                                                                                            AUDI
                                                                                                            BENTLEY
                                                                                                            BMW
                                                                                                            CHERY
                                                                                                            CHEVROLET
                                                                                                            CHRYSLER
                                                                                                            DAEWOO
                                                                                                            DAIHATSU
                                                                                                            DODGE
                                                                                                            FORD
                                                                                                            GEELY
                                                                                                            HONDA
                                                                                                            HYUNDAI
                                                                                                            INFINITI
                                                                                                            ISUZU
                                                                                                            JAGUAR
                                                                                                            JEEP
                                                                                                            KIA
                                                                                                            LAND ROVER
                                                                                                            LEXUS
                                                                                                            MAZDA
                                                                                                            MERCEDES
                                                                                                            MINI
                                                                                                            MITSUBISHI
                                                                                                            NISSAN
                                                                                                            PEUGEOT
                                                                                                            PORSCHE
                                                                                                            PROTON
                                                                                                            RENAULT
                                                                                                            SAAB
                                                                                                            SMART
                                                                                                            SSANGYONG
                                                                                                            SUBARU
                                                                                                            SUZUKI
                                                                                                            TOYOTA
                                                                                                            VOLKSWAGEN
                                                                                                            VOLVO
                                                                                                    ' or . = '
                                                    Pilih Merk Mobil*
                                                                                                            AUDI
                                                                                                            BENTLEY
                                                                                                            BMW
                                                                                                            CHERY
                                                                                                            CHEVROLET
                                                                                                            CHRYSLER
                                                                                                            DAEWOO
                                                                                                            DAIHATSU
                                                                                                            DODGE
                                                                                                            FORD
                                                                                                            GEELY
                                                                                                            HONDA
                                                                                                            HYUNDAI
                                                                                                            INFINITI
                                                                                                            ISUZU
                                                                                                            JAGUAR
                                                                                                            JEEP
                                                                                                            KIA
                                                                                                            LAND ROVER
                                                                                                            LEXUS
                                                                                                            MAZDA
                                                                                                            MERCEDES
                                                                                                            MINI
                                                                                                            MITSUBISHI
                                                                                                            NISSAN
                                                                                                            PEUGEOT
                                                                                                            PORSCHE
                                                                                                            PROTON
                                                                                                            RENAULT
                                                                                                            SAAB
                                                                                                            SMART
                                                                                                            SSANGYONG
                                                                                                            SUBARU
                                                                                                            SUZUKI
                                                                                                            TOYOTA
                                                                                                            VOLKSWAGEN
                                                                                                            VOLVO
                                                                                                    ')]</value>
      <webElementGuid>fc21a20a-b812-458d-b12b-eb346c31c7ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
