<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_43_input copy form agree_AS</name>
   <tag></tag>
   <elementGuidId>1969843e-0891-4b8c-bdfa-313662c1e2e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_agree</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_agree']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb5871e4-84f5-4b83-a50c-fa3721711ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>16d87615-3e38-49d1-a424-a9d3b141be5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_agree</value>
      <webElementGuid>51d36bc3-6cc0-454c-ad61-4f5a4a73c448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_agree</value>
      <webElementGuid>37a9b79e-5ecc-49c8-be97-ebfa6476ddad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_agree&quot;)</value>
      <webElementGuid>6ac8c675-972e-4c01-b3b4-910f23676eb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_agree']</value>
      <webElementGuid>8f332a41-0244-41df-bd9b-b2e9f4c68d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCheckingForm']/div[19]/div[2]/input</value>
      <webElementGuid>c853e243-a3b9-4927-88eb-5b2e91aab452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7b8ab9fa-afe7-440a-8d33-78c8a4d973b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'form_agree' and @id = 'form_agree']</value>
      <webElementGuid>24e89060-9113-435c-8630-a559fb6ca4d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
