<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website MLCI_34_Pilih Model Mobil_AS</name>
   <tag></tag>
   <elementGuidId>913fc34d-513e-4918-8cd5-bc98da5b049c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modelmobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='modelmobil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c06cac4e-80f0-4cd9-a9b4-6b63217893ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modelmobil</value>
      <webElementGuid>7383e94e-ed8a-41b0-a328-3170beb9d43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modelmobil</value>
      <webElementGuid>2d4f593d-fa2b-4784-847e-57682308fcda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid form-control</value>
      <webElementGuid>db982b9d-c90b-490c-ac35-705c944043fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Model Mobil*ClioKangooMeganeScenic</value>
      <webElementGuid>a4416a4f-4b9f-4190-a579-92ba7dcf6b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modelmobil&quot;)</value>
      <webElementGuid>ea6224b1-e1a7-4ce0-9966-b63242ead9f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='modelmobil']</value>
      <webElementGuid>f6d14a7e-29ab-4310-8786-ffa803f95e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div[12]/div[2]/p/select</value>
      <webElementGuid>1c19eee7-5e0b-4660-aa37-72053278db5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model Mobil'])[1]/following::select[1]</value>
      <webElementGuid>9d5c1429-5054-4dad-84b9-e64209324272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merk Mobil'])[1]/following::select[2]</value>
      <webElementGuid>366afe60-d90b-4923-bd8d-55a718c934b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Mobil'])[1]/preceding::select[1]</value>
      <webElementGuid>9a74b60c-0e7a-45a1-849f-ba4c00a58072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[2]/preceding::select[2]</value>
      <webElementGuid>95ccdc3c-880f-4bdc-a290-3caedc09ee50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/p/select</value>
      <webElementGuid>6ab8fa81-877e-4cc2-93ab-48404cc0bb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'modelmobil' and @id = 'modelmobil' and (text() = 'Pilih Model Mobil*ClioKangooMeganeScenic' or . = 'Pilih Model Mobil*ClioKangooMeganeScenic')]</value>
      <webElementGuid>734d60eb-e3ba-4978-a2cf-5c35a9a5c8a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
